collector:
  endpoint: "wss://gateway.saxo"
  symbols:
    - "EURUSD"

storage:
  database: "data/forex.db"

aggregator:
  intervals: [60, 300, 900]

strategy:
  # Lookbacks & thresholds
  rsi_period:        20
  sma_period:        20
  trend_window:      30
  macd_fast:         12
  macd_slow:         26
  macd_signal:       9
  bollinger_period:  20
  bollinger_std_dev: 2

  # Strategy execution parameters
  cooldown_seconds:  60
  min_trade_gap:     0.0001
  hysteresis_margin: -0.1
  macd_tolerance:    0.000002

  # Trade control (formerly hard-coded in tester)
  min_profit_pips:   0.0001
  min_hold_seconds:  120

  # Weights
  weights:
    rsi:          0.15
    trend:        0.15
    sma:          0.1
    macd:         0.1
    bollinger:    0.1
    pattern:      0.1
    candle_1m:    0.1
    candle_5m:    0.1
    candle_15m:   0.2

  # Buy/sell thresholds
  thresholds:
    rsi_buy:    40
    rsi_sell:   60
    slope_buy:  0.0000015
    slope_sell: -0.0000015

backtest:
  start: "2025-01-01T00:00:00"
 # optional end: "2025-05-20T23:59:59"

executor:
  slippage: 0.0001
